---
title: "Getting Started"
format:
  html:
    include-in-header:
      - '_download.html'
---

Positron is a modern, extensible IDE for data science built on [Code OSS](https://github.com/microsoft/vscode). It combines the power of a full-featured IDE with interactive data science tools for Python and R.


#### Positron might be a good fit for you if you...

-   use VS Code for data science (Python or R) but wish it included more interactive affordances for data-specific tasks like running exploratory code, examining your variables and datasets, interacting with your plots, and developing data apps such as Shiny, Streamlit, or FastAPI.
-   use JupyterLab or hosted notebook tools for data science (Python or R) and are ready for a more powerful, fully-featured IDE that still supports notebooks.
-   use RStudio and want more ability to customize or extend your IDE.
-   use additional languages beyond only Python or R in your day-to-day data science or package development work, like Rust, C++, JavaScript, or Lua.
-   want access to powerful, data-science specific AI integrations in a modern, extensible IDE.

## Prerequisites
::: {.panel-tabset}

### Windows

If you're using Windows, make sure you have the [latest Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) installed.

### Python setup
Positron works with [actively supported versions](https://devguide.python.org/versions/#versions) of Python, from 3.9 to 3.13.  

We recommend [pyenv](https://github.com/pyenv/pyenv) and [pyenv for Windows](https://github.com/pyenv-win/pyenv-win) for managing Python versions.  

Positron requires the [IPython kernel](https://pypi.org/project/ipykernel/) (version 6.19.1 or higher) to communicate with Python. By default, the IPython kernel is bundled with Positron for the CPython implementation (the standard Python implementation) and added to the [Python search path](https://docs.python.org/3/library/sys_path_init.html).

If you prefer finer control over your Python environment, set the [`python.useBundledIpykernel` setting](positron://settings/python.useBundledIpykernel) to false and install the IPython kernel manually

::: callout-note
If you're using an implementation other than CPython, you'll need to install the IPython kernel manually. 
:::

### R setup

If you plan to use R with Positron, ensure you have R 4.2 or higher installed. To install R, follow the instructions for your operating system at <https://cloud.r-project.org/>.

Alternatively, if you'd like to have multiple R installations, [rig](https://github.com/r-lib/rig) is a great tool to manage this which works well with Positron.

If you're an R package developer, you will also want to make sure that you have the current versions of certain R packages, all of which had recent updates to make them work more smoothly in Positron. Run one of the code snippets below to ensure that you are up-to-date:

``` r
# if you're a pak person (we are!)
pak::pak(c("usethis", "cli", "crayon", "rlang", "roxygen2", "pkgload"))

# or using base R
install.packages(c("usethis", "cli", "crayon", "rlang", "roxygen2", "pkgload"))
```

::: callout-note
If you're a Windows user, note that Positron doesn't currently bundle [Rtools](https://cran.r-project.org/bin/windows/Rtools/). If you need Rtools for your package development or other work, you can either use the official guidance from CRAN on installing Rtools and putting it on the PATH, or alternatively, use [rig](https://github.com/r-lib/rig) to install and set up Rtools:

```bash
rig system rtools add
```
:::

:::

## Install Positron

Download the installer for your operating system from the button below and follow the standard installation process for your platform. You only need to install Positron once, as it automatically updates to the latest version after installation.

:::{.callout-important #privacy-policy}
## Accept license agreement

Please review [Positron's license agreement](licensing.qmd) and [privacy policy](https://posit.co/about/privacy-policy/). Your acceptance of this license agreement and privacy policy is required as a condition to proceeding with your download or use of the software.

<div id="privacy-policy-agreement"> 
  <input type="checkbox" id="privacy-checkbox" onclick="updatePrivacy(this)">
  <label>I agree to the <a href="licensing.qmd">Positron license agreement</a> and <a href="https://posit.co/about/privacy-policy/">Posit Privacy Policy</a>.</label>
</div>
:::

<!-- The below R code is used by the _download.html snippet 
to populate the platform-default download button -->
```{r}
#| echo: false
positronVersion <- Sys.getenv("RELEASE_VERSION")
```

[Download Positron <span id="os-name"></span>](#){.btn .btn-primary .disabled #download-btn data-version="`{r} positronVersion`"}

[All Downloads](download.qmd){#all-downloads}
<!-- TODO: Can we insert release notes in the Downloads page? -->

<!-- ## Migrating from other IDEs

If you are coming from another IDE, check out the migration guides to help you get started with Positron:

[Migrating from RStudio](#){.btn .btn-primary}
[Migrating from VS Code](#){.btn .btn-primary} -->
<!-- TODO: Uncomment when these pages are ready -->
