---
title: "Download Positron"
format:
  html:
    include-in-header:
      - '_download.html'

---

## Positron on desktop

Find out what you need to know to [get started](start.qmd) using Positron, then download the desktop installer for your platform.

::: callout-important
## Accept license agreement

Please review [Positron's license agreement](licensing.qmd) and [privacy policy](https://posit.co/about/privacy-policy/). Your acceptance of this license agreement and privacy policy is required as a condition to proceeding with your download or use of the software.

<div id="privacy-policy-agreement">
  <input type="checkbox" id="privacy-checkbox" onclick="updatePrivacy(this)">
  <label>I agree to the [Positron license agreement](licensing.qmd) and [Posit Privacy Policy](https://posit.co/about/privacy-policy/).</label>
</div>
:::


```{r, id='download-table'}
#| echo: false
#| warning: false
#| classes: plain

library(purrr)
library(glue)
library(httr)
library(jsonlite)

# Read release version from _environment
release_version <- Sys.getenv("RELEASE_VERSION")

# Create URLs
cdn_url <- "https://cdn.posit.co/positron/releases/" # Keep this in sync with cdnUrl in _download.html

#######################################################################################
# NOTE: please also check start.qmd and _download.html when updating the various URLs,
# to ensure that we are constructing these URLs consistently in both places.
#######################################################################################

windows_system <- glue("Positron-{release_version}-Setup.exe")
windows_user <- glue("Positron-{release_version}-UserSetup.exe")
macos_universal <- glue("Positron-{release_version}-universal.dmg")
macos_arm64 <- glue("Positron-{release_version}-arm64.dmg")
macos_x64 <- glue("Positron-{release_version}-x64.dmg")
debian_x64 <- glue("Positron-{release_version}-x64.deb")
debian_arm <- glue("Positron-{release_version}-arm64.deb")
redhat_x64 <- glue("Positron-{release_version}-x64.rpm")
redhat_arm <- glue("Positron-{release_version}-arm64.rpm")
urls <- list(
  glue("{cdn_url}win/x86_64/{windows_system}"),
  glue("{cdn_url}win/x86_64/{windows_user}"),
  glue("{cdn_url}mac/universal/{macos_universal}"),
  glue("{cdn_url}mac/arm64/{macos_arm64}"),
  glue("{cdn_url}mac/x64/{macos_x64}"),
  glue("{cdn_url}deb/x86_64/{debian_x64}"),
  glue("{cdn_url}deb/arm64/{debian_arm}"),
  glue("{cdn_url}rpm/x86_64/{redhat_x64}"),
  glue("{cdn_url}rpm/arm64/{redhat_arm}")
)

# Get checksums
checksum_data <- rlang::try_fetch(
  fromJSON(glue("{cdn_url}checksums/positron-{release_version}-checksums.json")), 
  error = function(cnd) list(),
  warning = function(cnd) list()
)
all_installers <- list(
  windows_system,
  windows_user,
  macos_universal,
  macos_arm64,
  macos_x64,
  debian_x64,
  debian_arm,
  redhat_x64,
  redhat_arm
)
checksums <- map_chr(all_installers, ~ pluck(checksum_data, .))
checksums_short <- substr(checksums, 1, 7)

# Get file sizes
cloudfront_headers <- map(urls, HEAD) |> map(headers)
file_sizes <- map(cloudfront_headers, "content-length") |>
  map(fs::fs_bytes) |>
  map_chr(as.character)
file_names_only <- stringr::str_extract(urls, "[^\\/]+$")

markdown_links <- glue('<a href="{urls}">{file_names_only}</a>')

# Create base table without checksums
download_table <- data.frame(
  Platform = c(
    "Windows 10, 11 x64 (system level install)",
    "Windows 10, 11 x64 (user level install)",
    "MacOS 11.0+ (universal)",
    "MacOS 11.0+ (arm64/Apple Silicon)",
    "MacOS 11.0+ (x64/Intel)",
    "Debian-based Linux x64 (Ubuntu 20+)",
    "Debian-based Linux arm64 (Ubuntu 20+)",
    "Red Hat-based Linux x64 (RHEL9)",
    "Red Hat-based Linux arm64 (RHEL9)"
  ),
  Download = markdown_links,
  Size = file_sizes
)

# Add checksums column if data is available
if (length(checksums) > 0) {
  download_table$`SHA-256` <- glue(
    '<span class="checksum" onclick="copyChecksum(\'{checksums}\', this)" title="Click to copy full checksum">{checksums_short}</span>'
  )
}

knitr::kable(download_table, format = "html", escape = FALSE)
```
<br>

Once you install Positron, it will [automatically check for updates moving forward](updating.qmd).

## Positron Pro on Posit Workbench

[Posit Workbench](https://posit.co/products/enterprise/workbench/) 2024.12.1 and later includes preview support for Positron Pro. To configure and use Positron Pro on Posit Workbench, please see the [Posit Workbench Administration Guide](https://docs.posit.co/ide/server-pro/positron_sessions/) and the [Positron Pro user guide](https://docs.posit.co/ide/server-pro/user/positron/getting-started/).

## Release notes

{{< include release-notes/release.md >}}

## Older releases

Older releases [are available on GitHub](https://github.com/posit-dev/positron/releases), and you can also find the [release notes for previous versions](release-notes.qmd).