# Project setup
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"


# Execute setup
execute:
  freeze: auto



# Website setup
website:
  # title: "BIODAS"
  description: "BIODAS website"
  favicon: "images/logo/BIODAS-logo-webtab.png"
  back-to-top-navigation: true
  # Website setup >> URL
  site-url: https://biodas.net
  repo-url: https://github.com/thanhnguyentrung-ph/BIODAS-website
  repo-actions: [edit, source, issue]
  # Website setup >> Navigation Bar setup
  navbar: 
    # Website setup >> Logo
    logo: "images/logo/BIODAS-logo-horizontal-radius2.png"
    logo-href: https://biodas.net
    background: "#313D5D"
    foreground: "#FFFFFF"
    title: ""
    search: true

    left:
      # 1. About BIODAS
      - text: "Giới thiệu"
        menu:
        - text: "Giới thiệu BIODAS"
          href: "about/introduce.qmd"
        - text: "Sứ mệnh - Tầm nhìn - Giá trị cốt lõi"
          href: "about/mission-vision-value.qmd"
        - text: "Nhân sự"
          href: "about/team.qmd"
      # 2. BIODAS projects
      - text: "Hoạt động chuyên môn"
        href: "project/index.qmd"

      # 3. BIODAS resources
      - text: "Tài nguyên"
        href: "resource/index.qmd"

      # 4. Media and Communication
      - text: "Tin tức"
        menu:
        - text: "Sự kiện"
          href: "media/event.qmd"
        - text: "Tin tức"
          href: "media/news.qmd"
        - text: "Thông tin học bổng"
          href: "media/scholarship.qmd"

      # 5. Recruitment
      - text: "Tuyển dụng"
        href: "recruitment/index.qmd"

    right:
      # 9. Link to other BIODAS platforms
      - icon: envelope
        aria-label: BIODAS mail
        href: mailto:contact@biodas.net
      - icon: github
        aria-label: BIODAS GitHub
        href: https://github.com/thanhnguyentrung-ph/BIODAS-website
      - icon: linkedin
        aria-label: BIODAS LinkedIn
        href: https://www.linkedin.com/company/biodas-team/about/
      - icon: twitter-x
        aria-label: BIODAS Twitter/X
        href: abc
      - icon: facebook
        aria-label: BIODAS Facebook
        href: https://www.facebook.com/profile.php?id=61580207438020
      - icon: youtube
        aria-label: BIODAS Youtube
        href: https://www.youtube.com/@BIODAS-TEAM
      - icon: tiktok
        aria-label: BIODAS TikTok
        href: tiktok

  # Website setup >> Page-footer setup
  page-footer:
    background: "#313D5D"
    left: |
      [Bản quyền &copy; 2025 thuộc về Công ty Cổ phần Viện Nghiên cứu Khoa học và Dữ liệu Y sinh](other/lience.qmd)
    center: 
      - icon: envelope
        aria-label: BIODAS mail
        href: mailto:contact@biodas.net
      - icon: github
        aria-label: BIODAS GitHub
        href: https://github.com/thanhnguyentrung-ph/BIODAS-website
      - icon: linkedin
        aria-label: BIODAS LinkedIn
        href: https://www.linkedin.com/company/biodas-team/about/
      - icon: twitter-x
        aria-label: BIODAS Twitter/X
        href: abc
      - icon: facebook
        aria-label: BIODAS Facebook
        href: https://www.facebook.com/profile.php?id=61580207438020
      - icon: youtube
        aria-label: BIODAS Youtube
        href: https://www.youtube.com/@BIODAS-TEAM
      - icon: tiktok
        aria-label: BIODAS TikTok
        href: tiktok
      - icon: rss
        aria-label: BIODAS RSS
        href: other/feeds.html
    right: |
      [Terms & Conditions](other/ts-and-cs.qmd)
  
  # Website setup >> Side Bar setup
  sidebar:
    style: "docked"
    search: true





format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: scroll
    linkcolor: "#313D5D"
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px



babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: vi
    text: "Tiếng Việt"
  - name: en
    text: "English"
  mainlanguage: "vi"
  languages: ["en"]
title-en: ""
description-en: "BIODAS official website in English"
author-en: author in en
lang: vn



